<div class="p-4">

    @push('styles')
        <style>
            /* .stat-card {
                                                                                                                                                                                                                                                                                                                        border-radius: 16px;
                                                                                                                                                                                                                                                                                                                        border: none;
                                                                                                                                                                                                                                                                                                                        transition: transform .2s, box-shadow .2s;
                                                                                                                                                                                                                                                                                                                        overflow: hidden;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .stat-card:hover {
                                                                                                                                                                                                                                                                                                                        transform: translateY(-4px);
                                                                                                                                                                                                                                                                                                                        box-shadow: 0 12px 28px rgba(0, 0, 0, .1) !important;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .stat-icon {
                                                                                                                                                                                                                                                                                                                        width: 52px;
                                                                                                                                                                                                                                                                                                                        height: 52px;
                                                                                                                                                                                                                                                                                                                        border-radius: 14px;
                                                                                                                                                                                                                                                                                                                        display: flex;
                                                                                                                                                                                                                                                                                                                        align-items: center;
                                                                                                                                                                                                                                                                                                                        justify-content: center;
                                                                                                                                                                                                                                                                                                                        font-size: 22px;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .ticket-row:hover {
                                                                                                                                                                                                                                                                                                                        background: #f8f9fa;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .agent-avatar {
                                                                                                                                                                                                                                                                                                                        width: 38px;
                                                                                                                                                                                                                                                                                                                        height: 38px;
                                                                                                                                                                                                                                                                                                                        border-radius: 50%;
                                                                                                                                                                                                                                                                                                                        display: flex;
                                                                                                                                                                                                                                                                                                                        align-items: center;
                                                                                                                                                                                                                                                                                                                        justify-content: center;
                                                                                                                                                                                                                                                                                                                        font-size: 13px;
                                                                                                                                                                                                                                                                                                                        font-weight: 600;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .bar-chart-bar {
                                                                                                                                                                                                                                                                                                                        border-radius: 6px 6px 0 0;
                                                                                                                                                                                                                                                                                                                        transition: opacity .2s;
                                                                                                                                                                                                                                                                                                                        min-height: 4px;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .bar-chart-bar:hover {
                                                                                                                                                                                                                                                                                                                        opacity: .8;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .rating-bar {
                                                                                                                                                                                                                                                                                                                        height: 6px;
                                                                                                                                                                                                                                                                                                                        border-radius: 10px;
                                                                                                                                                                                                                                                                                                                        background: #e9ecef;
                                                                                                                                                                                                                                                                                                                        overflow: hidden;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .rating-fill {
                                                                                                                                                                                                                                                                                                                        height: 100%;
                                                                                                                                                                                                                                                                                                                        border-radius: 10px;
                                                                                                                                                                                                                                                                                                                        background: #ffc107;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .stat-card {
                                                                                                                                                                                                                                                                                                                        border-radius: 18px;
                                                                                                                                                                                                                                                                                                                        border: none;
                                                                                                                                                                                                                                                                                                                        transition: transform .2s, box-shadow .2s;
                                                                                                                                                                                                                                                                                                                        overflow: hidden;
                                                                                                                                                                                                                                                                                                                        position: relative;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .stat-card:hover {
                                                                                                                                                                                                                                                                                                                        transform: translateY(-5px);
                                                                                                                                                                                                                                                                                                                        box-shadow: 0 16px 32px rgba(0, 0, 0, .1) !important;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .stat-card .icon-box {
                                                                                                                                                                                                                                                                                                                        width: 52px;
                                                                                                                                                                                                                                                                                                                        height: 52px;
                                                                                                                                                                                                                                                                                                                        border-radius: 14px;
                                                                                                                                                                                                                                                                                                                        display: flex;
                                                                                                                                                                                                                                                                                                                        align-items: center;
                                                                                                                                                                                                                                                                                                                        justify-content: center;
                                                                                                                                                                                                                                                                                                                        font-size: 22px;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .stat-card .card-stripe {
                                                                                                                                                                                                                                                                                                                        height: 4px;
                                                                                                                                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .ticket-item {
                                                                                                                                                                                                                                                                                                                        border-radius: 14px;
                                                                                                                                                                                                                                                                                                                        border: 1px solid rgba(0, 0, 0, .06);
                                                                                                                                                                                                                                                                                                                        transition: box-shadow .2s, transform .15s;
                                                                                                                                                                                                                                                                                                                        background: #fff;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .ticket-item:hover {
                                                                                                                                                                                                                                                                                                                        box-shadow: 0 6px 20px rgba(0, 0, 0, .08);
                                                                                                                                                                                                                                                                                                                        transform: translateY(-2px);
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .status-dot {
                                                                                                                                                                                                                                                                                                                        width: 8px;
                                                                                                                                                                                                                                                                                                                        height: 8px;
                                                                                                                                                                                                                                                                                                                        border-radius: 50%;
                                                                                                                                                                                                                                                                                                                        display: inline-block;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .welcome-card {
                                                                                                                                                                                                                                                                                                                        background: linear-gradient(135deg, #0d6efd 0%, #0a58ca 100%);
                                                                                                                                                                                                                                                                                                                        border-radius: 20px;
                                                                                                                                                                                                                                                                                                                        border: none;
                                                                                                                                                                                                                                                                                                                        overflow: hidden;
                                                                                                                                                                                                                                                                                                                        position: relative;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .welcome-card::before {
                                                                                                                                                                                                                                                                                                                        content: '';
                                                                                                                                                                                                                                                                                                                        position: absolute;
                                                                                                                                                                                                                                                                                                                        top: -40px;
                                                                                                                                                                                                                                                                                                                        right: -40px;
                                                                                                                                                                                                                                                                                                                        width: 180px;
                                                                                                                                                                                                                                                                                                                        height: 180px;
                                                                                                                                                                                                                                                                                                                        border-radius: 50%;
                                                                                                                                                                                                                                                                                                                        background: rgba(255, 255, 255, .08);
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .welcome-card::after {
                                                                                                                                                                                                                                                                                                                        content: '';
                                                                                                                                                                                                                                                                                                                        position: absolute;
                                                                                                                                                                                                                                                                                                                        bottom: -30px;
                                                                                                                                                                                                                                                                                                                        right: 60px;
                                                                                                                                                                                                                                                                                                                        width: 120px;
                                                                                                                                                                                                                                                                                                                        height: 120px;
                                                                                                                                                                                                                                                                                                                        border-radius: 50%;
                                                                                                                                                                                                                                                                                                                        background: rgba(255, 255, 255, .05);
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .quick-action {
                                                                                                                                                                                                                                                                                                                        border-radius: 14px;
                                                                                                                                                                                                                                                                                                                        border: 1.5px dashed rgba(13, 110, 253, .3);
                                                                                                                                                                                                                                                                                                                        background: rgba(13, 110, 253, .03);
                                                                                                                                                                                                                                                                                                                        transition: all .2s;
                                                                                                                                                                                                                                                                                                                        cursor: pointer;
                                                                                                                                                                                                                                                                                                                        text-decoration: none;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .quick-action:hover {
                                                                                                                                                                                                                                                                                                                        border-color: #0d6efd;
                                                                                                                                                                                                                                                                                                                        background: rgba(13, 110, 253, .08);
                                                                                                                                                                                                                                                                                                                        transform: translateY(-2px);
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .progress-thin {
                                                                                                                                                                                                                                                                                                                        height: 6px;
                                                                                                                                                                                                                                                                                                                        border-radius: 10px;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .avatar-circle {
                                                                                                                                                                                                                                                                                                                        width: 46px;
                                                                                                                                                                                                                                                                                                                        height: 46px;
                                                                                                                                                                                                                                                                                                                        border-radius: 50%;
                                                                                                                                                                                                                                                                                                                        background: linear-gradient(135deg, #0d6efd, #6ea8fe);
                                                                                                                                                                                                                                                                                                                        display: flex;
                                                                                                                                                                                                                                                                                                                        align-items: center;
                                                                                                                                                                                                                                                                                                                        justify-content: center;
                                                                                                                                                                                                                                                                                                                        font-size: 16px;
                                                                                                                                                                                                                                                                                                                        font-weight: 700;
                                                                                                                                                                                                                                                                                                                        color: #fff;
                                                                                                                                                                                                                                                                                                                        flex-shrink: 0;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    .bg-success-subtle  { background-color: #d1e7dd !important; }
                                                                                                                                                                                                                                                                                                                    .bg-warning-subtle  { background-color: #fff3cd !important; }
                                                                                                                                                                                                                                                                                                                    .bg-danger-subtle   { background-color: #f8d7da !important; }
                                                                                                                                                                                                                                                                                                                    .bg-secondary-subtle{ background-color: #e2e3e5 !important; } */
        </style>
    @endpush

    {{-- ===================== WELCOME ===================== --}}
    <div class="welcome-card p-4 mb-4 shadow-sm">
        <div class="d-flex align-items-center justify-content-between">
            <div style="position: relative; z-index: 1;">
                <p class="text-white text-opacity-75 mb-1 small">
                    {{ now()->format('l, d M Y') }}
                </p>
                <h4 class="text-white fw-bold mb-1">
                    👋 {{ __('Welcome back') }}, {{ Auth::user()->name }}!
                </h4>
                <p class="text-white text-opacity-75 mb-3 small">
                    {{ __('Track and manage your support tickets from here.') }}
                </p>
            </div>
            <div class="d-none d-md-block text-white" style="position: relative; z-index: 1;">
                <i class="fa fa-calendar me-1"></i> {{ now()->format('l, d M Y') }}
            </div>
        </div>
    </div>

    {{-- =================== Pages ======================== --}}
    <div class="row mb-3">
        <div class="col-lg-12 ">
            <div class="d-flex gap-2">
                <a wire:click="changePage('assetsDashboard')"
                    class="btn {{ $page == 'assetsDashboard' ? 'btn-info' : '' }}">
                    <i class="fa-solid fa-laptop"></i>
                    Assets</a>
                <a wire:click="changePage('ticketsDashboard')"
                    class="btn {{ $page == 'ticketsDashboard' ? 'btn-success' : '' }}">
                    <i class="fa-solid fa-ticket"></i>
                    Tickets</a>
            </div>
        </div>
    </div>

    {{-- ============================ Assets Cards ============================== --}}
    {{-- TODO: Implement Assets Dashboard --}}
    @switch($page)
        @case('assetsDashboard')
            @include('livewire.v1.admin.asset-dashboard')
        @break

        @case('ticketsDashboard')
            @include('livewire.v1.admin.ticket-dashboard')
        @break

        @default
    @endswitch






</div>
